### ISSUE TITLE
This code seems to be newer https://github.com/adafruit/Adafruit-MCP23017-Arduino-Library

### ISSUE THREAD

**Issue by Blonder** [adafruit/Adafruit-RGB-LCD-Shield-Library#12]
Is there a reason why the MCP23017 library in the Adafruit-RGB-LCD-Shield-Library project and in the Adafruit-MCP23017-Arduino-Library project are different, or should they be synced?
Thanks for the help.

**Comment by ladyada** [comment]
yeah its basically 'embedded' - seemed like a good idea at the time, easier to install :)
