### ISSUE TITLE
arduino due + Adafruit-RGB-LCD-Shield-Library not display the program hello world with SDA (20) and SCL(21)

### ISSUE THREAD

**Issue by rafaccount123** [adafruit/Adafruit-RGB-LCD-Shield-Library#14]
Hello,

I'm trying to display the program Hello world [https://github.com/adafruit/Adafruit-RGB-LCD-Shield-Library/blob/master/examples/HelloWorld/HelloWorld.ino](url) with the Adafruit-RGB-LCD-Shield [https://www.adafruit.com/product/714](url) with the SDA (20) and the SCL (21) but is not working.

The shield is correctly powered. I think that the issue is in the following code:
[https://github.com/adafruit/Adafruit-RGB-LCD-Shield-Library/blob/master/Adafruit_RGBLCDShield.cpp](url)

`
#include "Adafruit_RGBLCDShield.h"

#include <stdio.h>
#include <string.h>
#include <inttypes.h>
#include <Wire.h>
#ifdef __SAM3X8E__ // Arduino Due
 #define WIRE Wire1
#else 
 #define WIRE Wire
#endif

#if ARDUINO >= 100
 #include "Arduino.h"
#else
 #include "WProgram.h"
#endif
`
When the code define Wire Wire1 for the arduino Due, therefore the pins SDA (20) and SCL (21) cannot be used. Only the pins SCL1 and SDA1. 
While I would like to use the pins SCL1 and SDA1 and SDA (20) and SCL (21).

Can you change the line  #define WIRE Wire1 to use the four pins ?

Thanks for the help .

**Comment by ladyada** [comment]
hi, the pins in the I2C pad location are SDA1/SCL1 so Wire1 is correct
http://www.robgray.com/temp/Due-pinout-WEB.png
if you have tech support questions, please post in the forums :)
