### ISSUE TITLE
Not sure if it works with product/1115

### ISSUE THREAD

**Issue by scls19fr** [adafruit/Adafruit-RGB-LCD-Shield-Library#9]
Hello,

I bought https://www.adafruit.com/product/1115
LCD Shield Kit w/ 16x2 Character Display - Only 2 pins used! - BLUE AND WHITE

It's not very clear if code example in this project can be use to test this LCD/keypad shield.

I tried to compile and run [example](https://github.com/adafruit/Adafruit-RGB-LCD-Shield-Library/blob/master/examples/HelloWorld/HelloWorld.ino).

At startup, backlight is on but nothing appears on screen.

Any idea?

**Comment by ladyada** [comment]
hiya for tech support please post in the forums
https://forums.adafruit.com
thanks!

**Comment by scls19fr** [comment]
Ok sorry.
Here is forum thread https://forums.adafruit.com/viewtopic.php?f=47&t=118064
